"""
Performance Optimizer for Termux PXE Boot
Handles system optimization and performance tuning
"""
import os
import subprocess
import json
import time
from datetime import datetime

class PerformanceOptimizer:
    def __init__(self, settings=None, logger=None):
        self.settings = settings
        self.logger = logger
        self.optimization_dir = "/data/data/com.termux/files/home/.termux_pxe_boot/optimizations"
        self.profiles_dir = os.path.join(self.optimization_dir, "profiles")
        os.makedirs(self.profiles_dir, exist_ok=True)
        
    def create_performance_profiles(self):
        """Create performance optimization profiles"""
        profiles = {
            "maximum": {
                "name": "Maximum Performance",
                "description": "Ultimate performance configuration for gaming and intensive tasks",
                "config": {
                    "cpu_governor": "performance",
                    "memory_limit": 0,  # No limit
                    "swap_enabled": False,
                    "cache_size": "maximum",
                    "io_scheduler": "noop",
                    "network_buffers": "large",
                    "gpu_acceleration": True,
                    "preload": True,
                    "transparent_huge_pages": "always"
                }
            },
            "balanced": {
                "name": "Balanced Performance",
                "description": "Balanced performance for general use",
                "config": {
                    "cpu_governor": "balanced",
                    "memory_limit": 0.8,  # 80% of available
                    "swap_enabled": True,
                    "swap_size": 2,  # 2GB
                    "cache_size": "normal",
                    "io_scheduler": "mq-deadline",
                    "network_buffers": "normal",
                    "gpu_acceleration": True,
                    "preload": True,
                    "transparent_huge_pages": "madvise"
                }
            },
            "minimal": {
                "name": "Minimal Power",
                "description": "Power-saving configuration for battery life",
                "config": {
                    "cpu_governor": "powersave",
                    "memory_limit": 0.6,  # 60% of available
                    "swap_enabled": False,
                    "cache_size": "minimal",
                    "io_scheduler": "bfq",
                    "network_buffers": "small",
                    "gpu_acceleration": False,
                    "preload": False,
                    "transparent_huge_pages": "never"
                }
            },
            "gaming": {
                "name": "Gaming Optimized",
                "description": "Performance tuned for gaming and multimedia",
                "config": {
                    "cpu_governor": "performance",
                    "memory_limit": 0.9,  # 90% of available
                    "swap_enabled": True,
                    "swap_size": 4,  # 4GB
                    "cache_size": "maximum",
                    "io_scheduler": "noop",
                    "network_buffers": "maximum",
                    "gpu_acceleration": True,
                    "preload": True,
                    "transparent_huge_pages": "always",
                    "rt_priority": True
                }
            }
        }
        
        # Save profiles to files
        for profile_name, profile_data in profiles.items():
            profile_file = os.path.join(self.profiles_dir, f"{profile_name}.json")
            with open(profile_file, 'w') as f:
                json.dump(profile_data, f, indent=2)
                
        self.logger.info("Performance profiles created")
        return profiles
        
    def create_system_optimization_script(self, profile="maximum"):
        """Create system optimization script based on profile"""
        script_content = f'''#!/bin/bash
# System Performance Optimization Script
# Generated by Termux PXE Boot - {profile.title()} Profile

set -e

echo "⚡ Starting system optimization ({profile} profile)..."

# Function to check if running as root
check_root() {{
    if [[ $EUID -ne 0 ]]; then
        echo "❌ This script must be run as root"
        exit 1
    fi
}}

# Function to backup system files
backup_files() {{
    echo "📋 Creating system backups..."
    cp /etc/sysctl.conf /etc/sysctl.conf.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
    cp /etc/default/grub /etc/default/grub.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
    echo "✅ Backup completed"
}}

# CPU optimization
optimize_cpu() {{
    echo "🔧 Optimizing CPU settings..."
    
    # Set CPU governor
    for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
        if [ -f "$cpu" ]; then
            echo "performance" > $cpu
        fi
    done
    
    # Disable CPU idle states for performance
    for cpu in /sys/devices/system/cpu/cpu*/cpuidle/state*/disable; do
        if [ -f "$cpu" ]; then
            echo 0 > $cpu 2>/dev/null || true
        fi
    done
    
    # Set process scheduling priority
    echo -1 > /proc/sys/kernel/sched_rt_runtime_us
    
    echo "✅ CPU optimization completed"
}}

# Memory optimization
optimize_memory() {{
    echo "🧠 Optimizing memory settings..."
    
    # Memory management
    echo "10" > /proc/sys/vm/swappiness
    echo "50" > /proc/sys/vm/vfs_cache_pressure
    echo "3" > /proc/sys/vm/dirty_ratio
    echo "2" > /proc/sys/vm/dirty_background_ratio
    echo "3000" > /proc/sys/vm/dirty_expire_centisecs
    echo "500" > /proc/sys/vm/dirty_writeback_centisecs
    
    # Transparent huge pages
    echo "always" > /sys/kernel/mm/transparent_hugepage/enabled
    echo "always" > /sys/kernel/mm/transparent_hugepage/defrag
    
    # Disable overcommit
    echo "2" > /proc/sys/vm/overcommit_memory
    
    echo "✅ Memory optimization completed"
}}

# Network optimization
optimize_network() {{
    echo "🌐 Optimizing network settings..."
    
    # Network buffer sizes
    echo "134217728" > /proc/sys/net/core/rmem_max
    echo "134217728" > /proc/sys/net/core/wmem_max
    echo "5000" > /proc/sys/net/core/netdev_max_backlog
    
    # TCP optimizations
    echo "4096 65536 134217728" > /proc/sys/net/ipv4/tcp_rmem
    echo "4096 65536 134217728" > /proc/sys/net/ipv4/tcp_wmem
    
    # Congestion control
    echo "bbr" > /proc/sys/net/ipv4/tcp_congestion_control
    
    # Connection tracking
    echo "1000000" > /proc/sys/net/netfilter/nf_conntrack_max
    
    echo "✅ Network optimization completed"
}}

# I/O optimization
optimize_io() {{
    echo "💾 Optimizing I/O settings..."
    
    # Set deadline scheduler for all devices
    for device in /sys/block/*/queue/scheduler; do
        if [ -f "$device" ]; then
            echo "mq-deadline" > $device 2>/dev/null || true
        fi
    done
    
    # Optimize I/O elevator
    for queue in /sys/block/*/queue/iosched; do
        if [ -f "$queue" ]; then
            echo "deadline" > $queue 2>/dev/null || true
        fi
    done
    
    # File system optimizations
    echo "0" > /proc/sys/fs/xfs/age_buffer_centisecs 2>/dev/null || true
    echo "0" > /proc/sys/fs/xfs/symmetric_readahead 2>/dev/null || true
    
    echo "✅ I/O optimization completed"
}}

# Gaming-specific optimizations
if [[ "{profile}" == "gaming" ]]; then
    echo "🎮 Applying gaming-specific optimizations..."
    
    # Real-time scheduling
    echo "250" > /proc/sys/kernel/sched_latency_ns
    echo "2000000" > /proc/sys/kernel/sched_migration_cost_ns
    
    # Graphics optimizations
    echo "high" > /sys/class/graphics/fbcon/cursor_blink 2>/dev/null || true
    
    # Audio latency
    echo "0" > /proc/asound/card*/pcm*/sub*/status/hw_params 2>/dev/null || true
fi

# Power management (disabled for performance)
echo "⚡ Disabling power management for performance..."
systemctl disable bluetooth 2>/dev/null || true
systemctl disable cups 2>/dev/null || true
systemctl disable avahi-daemon 2>/dev/null || true
systemctl disable ModemManager 2>/dev/null || true

# Services to enable for performance
systemctl enable NetworkManager 2>/dev/null || true
systemctl enable preload 2>/dev/null || true

# Kernel parameters
optimize_kernel() {{
    echo "🔧 Applying kernel optimizations..."
    
    cat >> /etc/sysctl.d/99-performance.conf << 'EOF'
# Performance optimizations by Termux PXE Boot
# Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# Network performance
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.netdev_max_backlog = 5000
net.ipv4.tcp_rmem = 4096 65536 134217728
net.ipv4.tcp_wmem = 4096 65536 134217728
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3

# Memory management
vm.swappiness = 10
vm.vfs_cache_pressure = 50
vm.dirty_ratio = 3
vm.dirty_background_ratio = 2
vm.dirty_expire_centisecs = 3000
vm.dirty_writeback_centisecs = 500

# File system
fs.file-max = 2097152
fs.inotify.max_user_watches = 524288
fs.aio-max-nr = 1048576

# Kernel
kernel.sched_migration_cost_ns = 5000000
kernel.sched_min_granularity_ns = 15000000
kernel.sched_wakeup_granularity_ns = 2000000
kernel.sched_latency_ns = 250000
kernel.timer_migration = 0

# Security
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
EOF

    sysctl -p /etc/sysctl.d/99-performance.conf 2>/dev/null || true
    
    echo "✅ Kernel optimizations applied"
}}

# GPU optimization
optimize_gpu() {{
    echo "🎨 Optimizing GPU settings..."
    
    # NVIDIA optimizations
    if command -v nvidia-smi >/dev/null 2>&1; then
        nvidia-smi -pm 1 2>/dev/null || true
        nvidia-smi -ac 2000,700 2>/dev/null || true
    fi
    
    # AMD optimizations
    if [ -f /sys/class/drm/card0/device/power_dpm_state ]; then
        echo "performance" > /sys/class/drm/card0/device/power_dpm_state 2>/dev/null || true
    fi
    
    # Intel optimizations
    if [ -f /sys/class/drm/card0/device/gt_RP_min_freq_mhz ]; then
        echo "max" > /sys/class/drm/card0/device/gt_min_freq_mhz 2>/dev/null || true
    fi
    
    echo "✅ GPU optimization completed"
}}

# Preload optimization
setup_preload() {{
    echo "⚡ Setting up preload optimization..."
    
    # Configure preload
    cat > /etc/preload.conf << 'EOF'
# Preload configuration
# Generated by Termux PXE Boot

session session number
processes process number

# Memory settings
memory 50
mapping mapped memory

# Readahead settings
readahead readahead KB

# Schedule settings
schedpolicy sch policy
sch.reset_agestress_threshold sch reset threshold
sch.decay_sharpness sch decay
sch.decay_sharpness力度 sch decay
EOF

    systemctl enable preload 2>/dev/null || true
    systemctl start preload 2>/dev/null || true
    
    echo "✅ Preload optimization completed"
}}

# Create performance monitoring script
create_monitoring_script() {{
    echo "📊 Creating performance monitoring..."
    
    cat > /usr/local/bin/perf-monitor << 'EOF'
#!/bin/bash
# Performance Monitor
# Generated by Termux PXE Boot

clear
echo "🖥️  System Performance Monitor"
echo "================================"
echo "Date: $(date)"
echo "Uptime: $(uptime -p)"
echo ""

echo "💻 CPU Information:"
echo "Frequency: $(cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d: -f2 | xargs)"
echo "Governors: $(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null | sort -u)"
echo "Load Average: $(uptime | awk -F'load average:' '{{ print $2 }}')"
echo ""

echo "🧠 Memory Information:"
free -h
echo ""

echo "💾 Disk Information:"
df -h /
echo ""

echo "🌐 Network Information:"
echo "External IP: $(curl -s ifconfig.me 2>/dev/null || echo 'Not available')"
echo "Local IP: $(hostname -I | awk '{{ print $1 }}')"
echo ""

echo "🌡️  Temperature Information:"
sensors 2>/dev/null | grep -E 'Core|Package|tctl|tctl' | head -5 || echo "Sensors not available"
echo ""

echo "⚡ Performance Optimizations Active:"
if [ -f /proc/sys/vm/swappiness ]; then
    echo "Swapiness: $(cat /proc/sys/vm/swappiness)"
fi
if [ -f /sys/kernel/mm/transparent_hugepage/enabled ]; then
    echo "THP: $(cat /sys/kernel/mm/transparent_hugepage/enabled | tr -d '[]')"
fi
if [ -f /proc/sys/kernel/sched_latency_ns ]; then
    echo "Scheduler Latency: $(cat /proc/sys/kernel/sched_latency_ns)ns"
fi
echo ""
EOF

    chmod +x /usr/local/bin/perf-monitor
    
    echo "✅ Performance monitoring created"
    echo "Run 'perf-monitor' command to view system performance"
}}

# Main execution
main() {{
    echo "🚀 Starting {profile.title()} Performance Optimization"
    echo "================================================="
    
    check_root
    backup_files
    optimize_cpu
    optimize_memory
    optimize_network
    optimize_io
    optimize_kernel
    optimize_gpu
    setup_preload
    create_monitoring_script
    
    echo ""
    echo "🎉 Performance optimization completed!"
    echo "✅ System is now optimized for {profile} performance"
    echo ""
    echo "Run 'perf-monitor' to check system performance"
    echo "Reboot recommended for full optimization to take effect"
}}

# Run main function
main "$@"
        '''
        
        # Create script directory
        script_dir = "/data/data/com.termux/files/home/pxe_assets/scripts"
        os.makedirs(script_dir, exist_ok=True)
        
        script_path = os.path.join(script_dir, f"optimize_{profile}.sh")
        with open(script_path, 'w') as f:
            f.write(script_content)
            
        # Make script executable
        os.chmod(script_path, 0o755)
        
        self.logger.info(f"Performance optimization script created for {profile} profile")
        return script_path
        
    def create_all_optimizations(self, profile="maximum"):
        """Create all performance optimizations"""
        try:
            # Create profiles
            profiles = self.create_performance_profiles()
            
            # Create optimization script
            script_path = self.create_system_optimization_script(profile)
            
            return {
                'profiles': profiles,
                'script': script_path,
                'profile_used': profile
            }
            
        except Exception as e:
            self.logger.error(f"Error creating performance optimizations: {e}")
            return NonePerformance Optimizer for Termux PXE Boot
Handles system optimization and performance tuning
"""
import os
import subprocess
import json
import time
from datetime import datetime

class PerformanceOptimizer:
    def __init__(self, settings=None, logger=None):
        self.settings = settings
        self.logger = logger
        self.optimization_dir = "/data/data/com.termux/files/home/.termux_pxe_boot/optimizations"
        self.profiles_dir = os.path.join(self.optimization_dir, "profiles")
        os.makedirs(self.profiles_dir, exist_ok=True)
        
    def create_performance_profiles(self):
        """Create performance optimization profiles"""
        profiles = {
            "maximum": {
                "name": "Maximum Performance",
                "description": "Ultimate performance configuration for gaming and intensive tasks",
                "config": {
                    "cpu_governor": "performance",
                    "memory_limit": 0,  # No limit
                    "swap_enabled": False,
                    "cache_size": "maximum",
                    "io_scheduler": "noop",
                    "network_buffers": "large",
                    "gpu_acceleration": True,
                    "preload": True,
                    "transparent_huge_pages": "always"
                }
            },
            "balanced": {
                "name": "Balanced Performance",
                "description": "Balanced performance for general use",
                "config": {
                    "cpu_governor": "balanced",
                    "memory_limit": 0.8,  # 80% of available
                    "swap_enabled": True,
                    "swap_size": 2,  # 2GB
                    "cache_size": "normal",
                    "io_scheduler": "mq-deadline",
                    "network_buffers": "normal",
                    "gpu_acceleration": True,
                    "preload": True,
                    "transparent_huge_pages": "madvise"
                }
            },
            "minimal": {
                "name": "Minimal Power",
                "description": "Power-saving configuration for battery life",
                "config": {
                    "cpu_governor": "powersave",
                    "memory_limit": 0.6,  # 60% of available
                    "swap_enabled": False,
                    "cache_size": "minimal",
                    "io_scheduler": "bfq",
                    "network_buffers": "small",
                    "gpu_acceleration": False,
                    "preload": False,
                    "transparent_huge_pages": "never"
                }
            },
            "gaming": {
                "name": "Gaming Optimized",
                "description": "Performance tuned for gaming and multimedia",
                "config": {
                    "cpu_governor": "performance",
                    "memory_limit": 0.9,  # 90% of available
                    "swap_enabled": True,
                    "swap_size": 4,  # 4GB
                    "cache_size": "maximum",
                    "io_scheduler": "noop",
                    "network_buffers": "maximum",
                    "gpu_acceleration": True,
                    "preload": True,
                    "transparent_huge_pages": "always",
                    "rt_priority": True
                }
            }
        }
        
        # Save profiles to files
        for profile_name, profile_data in profiles.items():
            profile_file = os.path.join(self.profiles_dir, f"{profile_name}.json")
            with open(profile_file, 'w') as f:
                json.dump(profile_data, f, indent=2)
                
        self.logger.info("Performance profiles created")
        return profiles
        
    def create_system_optimization_script(self, profile="maximum"):
        """Create system optimization script based on profile"""
        script_content = f'''#!/bin/bash
# System Performance Optimization Script
# Generated by Termux PXE Boot - {profile.title()} Profile

set -e

echo "⚡ Starting system optimization ({profile} profile)..."

# Function to check if running as root
check_root() {{
    if [[ $EUID -ne 0 ]]; then
        echo "❌ This script must be run as root"
        exit 1
    fi
}}

# Function to backup system files
backup_files() {{
    echo "📋 Creating system backups..."
    cp /etc/sysctl.conf /etc/sysctl.conf.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
    cp /etc/default/grub /etc/default/grub.backup.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
    echo "✅ Backup completed"
}}

# CPU optimization
optimize_cpu() {{
    echo "🔧 Optimizing CPU settings..."
    
    # Set CPU governor
    for cpu in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
        if [ -f "$cpu" ]; then
            echo "performance" > $cpu
        fi
    done
    
    # Disable CPU idle states for performance
    for cpu in /sys/devices/system/cpu/cpu*/cpuidle/state*/disable; do
        if [ -f "$cpu" ]; then
            echo 0 > $cpu 2>/dev/null || true
        fi
    done
    
    # Set process scheduling priority
    echo -1 > /proc/sys/kernel/sched_rt_runtime_us
    
    echo "✅ CPU optimization completed"
}}

# Memory optimization
optimize_memory() {{
    echo "🧠 Optimizing memory settings..."
    
    # Memory management
    echo "10" > /proc/sys/vm/swappiness
    echo "50" > /proc/sys/vm/vfs_cache_pressure
    echo "3" > /proc/sys/vm/dirty_ratio
    echo "2" > /proc/sys/vm/dirty_background_ratio
    echo "3000" > /proc/sys/vm/dirty_expire_centisecs
    echo "500" > /proc/sys/vm/dirty_writeback_centisecs
    
    # Transparent huge pages
    echo "always" > /sys/kernel/mm/transparent_hugepage/enabled
    echo "always" > /sys/kernel/mm/transparent_hugepage/defrag
    
    # Disable overcommit
    echo "2" > /proc/sys/vm/overcommit_memory
    
    echo "✅ Memory optimization completed"
}}

# Network optimization
optimize_network() {{
    echo "🌐 Optimizing network settings..."
    
    # Network buffer sizes
    echo "134217728" > /proc/sys/net/core/rmem_max
    echo "134217728" > /proc/sys/net/core/wmem_max
    echo "5000" > /proc/sys/net/core/netdev_max_backlog
    
    # TCP optimizations
    echo "4096 65536 134217728" > /proc/sys/net/ipv4/tcp_rmem
    echo "4096 65536 134217728" > /proc/sys/net/ipv4/tcp_wmem
    
    # Congestion control
    echo "bbr" > /proc/sys/net/ipv4/tcp_congestion_control
    
    # Connection tracking
    echo "1000000" > /proc/sys/net/netfilter/nf_conntrack_max
    
    echo "✅ Network optimization completed"
}}

# I/O optimization
optimize_io() {{
    echo "💾 Optimizing I/O settings..."
    
    # Set deadline scheduler for all devices
    for device in /sys/block/*/queue/scheduler; do
        if [ -f "$device" ]; then
            echo "mq-deadline" > $device 2>/dev/null || true
        fi
    done
    
    # Optimize I/O elevator
    for queue in /sys/block/*/queue/iosched; do
        if [ -f "$queue" ]; then
            echo "deadline" > $queue 2>/dev/null || true
        fi
    done
    
    # File system optimizations
    echo "0" > /proc/sys/fs/xfs/age_buffer_centisecs 2>/dev/null || true
    echo "0" > /proc/sys/fs/xfs/symmetric_readahead 2>/dev/null || true
    
    echo "✅ I/O optimization completed"
}}

# Gaming-specific optimizations
if [[ "{profile}" == "gaming" ]]; then
    echo "🎮 Applying gaming-specific optimizations..."
    
    # Real-time scheduling
    echo "250" > /proc/sys/kernel/sched_latency_ns
    echo "2000000" > /proc/sys/kernel/sched_migration_cost_ns
    
    # Graphics optimizations
    echo "high" > /sys/class/graphics/fbcon/cursor_blink 2>/dev/null || true
    
    # Audio latency
    echo "0" > /proc/asound/card*/pcm*/sub*/status/hw_params 2>/dev/null || true
fi

# Power management (disabled for performance)
echo "⚡ Disabling power management for performance..."
systemctl disable bluetooth 2>/dev/null || true
systemctl disable cups 2>/dev/null || true
systemctl disable avahi-daemon 2>/dev/null || true
systemctl disable ModemManager 2>/dev/null || true

# Services to enable for performance
systemctl enable NetworkManager 2>/dev/null || true
systemctl enable preload 2>/dev/null || true

# Kernel parameters
optimize_kernel() {{
    echo "🔧 Applying kernel optimizations..."
    
    cat >> /etc/sysctl.d/99-performance.conf << 'EOF'
# Performance optimizations by Termux PXE Boot
# Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# Network performance
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.netdev_max_backlog = 5000
net.ipv4.tcp_rmem = 4096 65536 134217728
net.ipv4.tcp_wmem = 4096 65536 134217728
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3

# Memory management
vm.swappiness = 10
vm.vfs_cache_pressure = 50
vm.dirty_ratio = 3
vm.dirty_background_ratio = 2
vm.dirty_expire_centisecs = 3000
vm.dirty_writeback_centisecs = 500

# File system
fs.file-max = 2097152
fs.inotify.max_user_watches = 524288
fs.aio-max-nr = 1048576

# Kernel
kernel.sched_migration_cost_ns = 5000000
kernel.sched_min_granularity_ns = 15000000
kernel.sched_wakeup_granularity_ns = 2000000
kernel.sched_latency_ns = 250000
kernel.timer_migration = 0

# Security
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
EOF

    sysctl -p /etc/sysctl.d/99-performance.conf 2>/dev/null || true
    
    echo "✅ Kernel optimizations applied"
}}

# GPU optimization
optimize_gpu() {{
    echo "🎨 Optimizing GPU settings..."
    
    # NVIDIA optimizations
    if command -v nvidia-smi >/dev/null 2>&1; then
        nvidia-smi -pm 1 2>/dev/null || true
        nvidia-smi -ac 2000,700 2>/dev/null || true
    fi
    
    # AMD optimizations
    if [ -f /sys/class/drm/card0/device/power_dpm_state ]; then
        echo "performance" > /sys/class/drm/card0/device/power_dpm_state 2>/dev/null || true
    fi
    
    # Intel optimizations
    if [ -f /sys/class/drm/card0/device/gt_RP_min_freq_mhz ]; then
        echo "max" > /sys/class/drm/card0/device/gt_min_freq_mhz 2>/dev/null || true
    fi
    
    echo "✅ GPU optimization completed"
}}

# Preload optimization
setup_preload() {{
    echo "⚡ Setting up preload optimization..."
    
    # Configure preload
    cat > /etc/preload.conf << 'EOF'
# Preload configuration
# Generated by Termux PXE Boot

session session number
processes process number

# Memory settings
memory 50
mapping mapped memory

# Readahead settings
readahead readahead KB

# Schedule settings
schedpolicy sch policy
sch.reset_agestress_threshold sch reset threshold
sch.decay_sharpness sch decay
sch.decay_sharpness力度 sch decay
EOF

    systemctl enable preload 2>/dev/null || true
    systemctl start preload 2>/dev/null || true
    
    echo "✅ Preload optimization completed"
}}

# Create performance monitoring script
create_monitoring_script() {{
    echo "📊 Creating performance monitoring..."
    
    cat > /usr/local/bin/perf-monitor << 'EOF'
#!/bin/bash
# Performance Monitor
# Generated by Termux PXE Boot

clear
echo "🖥️  System Performance Monitor"
echo "================================"
echo "Date: $(date)"
echo "Uptime: $(uptime -p)"
echo ""

echo "💻 CPU Information:"
echo "Frequency: $(cat /proc/cpuinfo | grep 'model name' | head -1 | cut -d: -f2 | xargs)"
echo "Governors: $(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor 2>/dev/null | sort -u)"
echo "Load Average: $(uptime | awk -F'load average:' '{{ print $2 }}')"
echo ""

echo "🧠 Memory Information:"
free -h
echo ""

echo "💾 Disk Information:"
df -h /
echo ""

echo "🌐 Network Information:"
echo "External IP: $(curl -s ifconfig.me 2>/dev/null || echo 'Not available')"
echo "Local IP: $(hostname -I | awk '{{ print $1 }}')"
echo ""

echo "🌡️  Temperature Information:"
sensors 2>/dev/null | grep -E 'Core|Package|tctl|tctl' | head -5 || echo "Sensors not available"
echo ""

echo "⚡ Performance Optimizations Active:"
if [ -f /proc/sys/vm/swappiness ]; then
    echo "Swapiness: $(cat /proc/sys/vm/swappiness)"
fi
if [ -f /sys/kernel/mm/transparent_hugepage/enabled ]; then
    echo "THP: $(cat /sys/kernel/mm/transparent_hugepage/enabled | tr -d '[]')"
fi
if [ -f /proc/sys/kernel/sched_latency_ns ]; then
    echo "Scheduler Latency: $(cat /proc/sys/kernel/sched_latency_ns)ns"
fi
echo ""
EOF

    chmod +x /usr/local/bin/perf-monitor
    
    echo "✅ Performance monitoring created"
    echo "Run 'perf-monitor' command to view system performance"
}}

# Main execution
main() {{
    echo "🚀 Starting {profile.title()} Performance Optimization"
    echo "================================================="
    
    check_root
    backup_files
    optimize_cpu
    optimize_memory
    optimize_network
    optimize_io
    optimize_kernel
    optimize_gpu
    setup_preload
    create_monitoring_script
    
    echo ""
    echo "🎉 Performance optimization completed!"
    echo "✅ System is now optimized for {profile} performance"
    echo ""
    echo "Run 'perf-monitor' to check system performance"
    echo "Reboot recommended for full optimization to take effect"
}}

# Run main function
main "$@"
        '''
        
        # Create script directory
        script_dir = "/data/data/com.termux/files/home/pxe_assets/scripts"
        os.makedirs(script_dir, exist_ok=True)
        
        script_path = os.path.join(script_dir, f"optimize_{profile}.sh")
        with open(script_path, 'w') as f:
            f.write(script_content)
            
        # Make script executable
        os.chmod(script_path, 0o755)
        
        self.logger.info(f"Performance optimization script created for {profile} profile")
        return script_path
        
    def create_all_optimizations(self, profile="maximum"):
        """Create all performance optimizations"""
        try:
            # Create profiles
            profiles = self.create_performance_profiles()
            
            # Create optimization script
            script_path = self.create_system_optimization_script(profile)
            
            return {
                'profiles': profiles,
                'script': script_path,
                'profile_used': profile
            }
            
        except Exception as e:
            self.logger.error(f"Error creating performance optimizations: {e}")
            return None
